name: 🚀 Deploy to 

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ ftpupload.net }}
          username: ${{ if0_40236585 }}
          password: ${{ G6hedRSKfQx7I }}
          server-dir: /htdocs/
          local-dir: ./public
